
CREATE TABLE IF NOT EXISTS User (
  user_id int NOT NULL AUTO_INCREMENT,
  user_name varchar(32) NOT NULL UNIQUE,
  email varchar(32) NOT NULL UNIQUE,
  name varchar(32) NOT NULL,
  biography varchar(255) DEFAULT NULL,
  password varchar(32) NOT NULL,
  PRIMARY KEY (user_id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS auth (
  date DATETIME NOT NULL,
  token varchar(32) NOT NULL,
  user_id int NOT NULL,
  FOREIGN KEY(user_id) REFERENCES User(user_id) ON DELETE CASCADE,
  PRIMARY KEY (token)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS Librarian(
  user_id INT PRIMARY KEY,
  FOREIGN KEY(user_id) REFERENCES User(user_id) ON DELETE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS Author(
  user_id INT PRIMARY KEY,
  FOREIGN KEY(user_id) REFERENCES User(user_id) ON DELETE CASCADE,
  is_verified BIT DEFAULT 0,
  verifier_id INT DEFAULT NULL,
  FOREIGN KEY(verifier_id) REFERENCES User(user_id) ON DELETE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS friend_of(
  user_id INT,
  FOREIGN KEY(user_id) REFERENCES User(user_id) ON DELETE CASCADE,
  friend_id INT,
  FOREIGN KEY(friend_id) REFERENCES User(user_id) ON DELETE CASCADE,
  accepted BIT DEFAULT 0,
  CONSTRAINT PK_Person PRIMARY KEY (user_id,friend_id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS Thread(
  tid int PRIMARY KEY AUTO_INCREMENT,
  name varchar(32) NOT NULL UNIQUE,
  context varchar(256) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS Post(
  pid INT PRIMARY KEY AUTO_INCREMENT,
  tid int NOT NULL,
  user_id int NOT NULL,
  like_count INT DEFAULT 0,
  title VARCHAR(64) NOT NULL,
  text VARCHAR(256) DEFAULT NULL,
  date DATETIME DEFAULT CURRENT_TIMESTAMP(),
  FOREIGN KEY(user_id) REFERENCES User(user_id) ON DELETE CASCADE,
  FOREIGN KEY(tid) REFERENCES Thread(tid) ON DELETE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS Comment(
  cid INT PRIMARY KEY AUTO_INCREMENT,
  user_id INT NOT NULL,
  text VARCHAR(256) NOT NULL,
  date DATETIME DEFAULT CURRENT_TIMESTAMP(),
  FOREIGN KEY(user_id) REFERENCES User(user_id) ON DELETE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS post_comment(
  cid INT PRIMARY KEY,
  pid INT NOT NULL,
  FOREIGN KEY(cid) REFERENCES Comment(cid) ON DELETE CASCADE,
  FOREIGN KEY(pid) REFERENCES Post(pid) ON DELETE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS Book(
  book_id INT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(64) NOT NULL,
  description VARCHAR(256) NOT NULL,
  genre VARCHAR(32) NOT NULL,
  year INT NOT NULL,
  img_url VARCHAR(64) DEFAULT NULL,
  pages INT NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS publishes(
  author_id INT,
  FOREIGN KEY(author_id) REFERENCES Author(user_id) ON DELETE CASCADE,
  book_id INT,
  FOREIGN KEY(book_id) REFERENCES Book(book_id) ON DELETE CASCADE,
  CONSTRAINT PK_Publishes PRIMARY KEY (author_id,book_id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS Edition(
  ed_id INT PRIMARY KEY AUTO_INCREMENT,
  book_id INT NOT NULL,
  FOREIGN KEY(book_id) REFERENCES Book(book_id) ON DELETE CASCADE,
  name VARCHAR(32) NOT NULL,
  format VARCHAR(32) NOT NULL,
  translator VARCHAR(32) DEFAULT NULL,
  language VARCHAR(32) NOT NULL,
  publish_date DATE NOT NULL,
  page INT NOT NULL,
  author_name VARCHAR(32) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS Series(
  ser_id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(32) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS series_of(
  book_id INT PRIMARY KEY,
  ser_id INT NOT NULL,
  FOREIGN KEY(book_id ) REFERENCES Book(book_id ) ON DELETE CASCADE,
  FOREIGN KEY(ser_id ) REFERENCES Series(ser_id ) ON DELETE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS Progress(
  pro_id INT PRIMARY KEY AUTO_INCREMENT,
  page_number INT NOT NULL,
  date DATETIME DEFAULT CURRENT_TIMESTAMP()
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS progress_comment(
  cid INT PRIMARY KEY,
  pro_id INT NOT NULL,
  FOREIGN KEY(cid ) REFERENCES Comment(cid ) ON DELETE CASCADE,
  FOREIGN KEY(pro_id ) REFERENCES Progress(pro_id ) ON DELETE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS mark_progress(
  user_id INT,
  FOREIGN KEY(user_id) REFERENCES User(user_id) ON DELETE CASCADE,
  book_id INT,
  FOREIGN KEY(book_id) REFERENCES Book(book_id) ON DELETE CASCADE,
  pro_id INT,
  FOREIGN KEY(pro_id) REFERENCES Progress(pro_id) ON DELETE CASCADE,
  CONSTRAINT PK_mark_progress PRIMARY KEY (user_id,book_id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS review(
  user_id INT,
  FOREIGN KEY(user_id) REFERENCES User(user_id) ON DELETE CASCADE,
  book_id INT,
  FOREIGN KEY(book_id ) REFERENCES Book(book_id ) ON DELETE CASCADE,
  rating INT NOT NULL,
  comment VARCHAR(256),
  reply VARCHAR(256) DEFAULT NULL,
  CONSTRAINT PK_review PRIMARY KEY (user_id,book_id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS Book_list(
  bl_id INT PRIMARY KEY AUTO_INCREMENT,
  user_id INT NOT NULL,
  FOREIGN KEY(user_id) REFERENCES User(user_id) ON DELETE CASCADE,
  name VARCHAR(32) NOT NULL,
  book_count INT DEFAULT 0
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS Challenge(
  chal_id INT PRIMARY KEY AUTO_INCREMENT,
  librarian_id INT NOT NULL,
  FOREIGN KEY(librarian_id) REFERENCES Librarian(user_id) ON DELETE CASCADE,
  bl_id INT NOT NULL,
  FOREIGN KEY(bl_id) REFERENCES Book_list(bl_id) ON DELETE CASCADE,
  challenge_name VARCHAR(32) NOT NULL,
  due_date DATE NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS recommend(
  user_id INT,
  FOREIGN KEY(user_id) REFERENCES User(user_id) ON DELETE CASCADE,
  book_id INT,
  FOREIGN KEY(friend_id) REFERENCES User(user_id) ON DELETE CASCADE,
  friend_id INT,
  FOREIGN KEY(book_id) REFERENCES Book(book_id) ON DELETE CASCADE,
  CONSTRAINT PK_recommend PRIMARY KEY (user_id,book_id,friend_id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS joins_challenge(
  user_id INT,
  FOREIGN KEY(user_id) REFERENCES User(user_id) ON DELETE CASCADE,
  chal_id INT,
  FOREIGN KEY(chal_id) REFERENCES Challenge(chal_id) ON DELETE CASCADE,
  book_read INT DEFAULT 0,
  CONSTRAINT PK_joins_challenge PRIMARY KEY (user_id,chal_id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



CREATE TABLE IF NOT EXISTS requests(
  book_id INT,
  FOREIGN KEY(book_id) REFERENCES Book(book_id) ON DELETE CASCADE,
  user_id INT,
  FOREIGN KEY(user_id) REFERENCES User(user_id) ON DELETE CASCADE,
  librarian_id INT,
  FOREIGN KEY(librarian_id) REFERENCES Librarian(user_id) ON DELETE CASCADE,
  request_msg VARCHAR(256) NOT NULL,
  approved BIT DEFAULT 0,
  CONSTRAINT PK_requests PRIMARY KEY (book_id,user_id,librarian_id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS has_books(
  book_id INT,
  FOREIGN KEY(book_id) REFERENCES Book(book_id) ON DELETE CASCADE,
  bl_id INT,
  FOREIGN KEY(bl_id) REFERENCES Book_list(bl_id) ON DELETE CASCADE,
  CONSTRAINT PK_Challenge PRIMARY KEY (book_id,bl_id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



CREATE TABLE IF NOT EXISTS follows(
  user_id INT,
  FOREIGN KEY(user_id) REFERENCES User(user_id) ON DELETE CASCADE,
  tid INT,
  FOREIGN KEY(tid) REFERENCES Thread(tid) ON DELETE CASCADE,
  CONSTRAINT PK_follows PRIMARY KEY (user_id,tid)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;




